permissions:
  contents: write


name: Bourse Automatique

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 6'  # tous les samedis à 8h du matin UTC (donc 10h à Paris l’été)

jobs:
  run-bourse-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          pip install requests pandas yfinance lxml

      - name: Run script
        run: |
          python bourse.py

      - name: Commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add resultats_bourse.csv
          git commit -m "Mise à jour des résultats boursiers [auto]" || echo "Rien à commiter"
          git push
